### ISSUE TITLE
How to use Chronicle Network Library with Solarflare Onload user space driver

### ISSUE THREAD

**Issue by NiinS** [OpenHFT/Chronicle-Network#101]
Hi,

We are planning to evaluate Chronicle-Network with a Solarflare SocketXtreme NIC. Wondering if you can share if we need any Onload specific API invocation from our Java code? Or do we need to keep the Onload in the Java library path at least?

Do you have any example we can follow?

I'm referring to this SO answer of @peter-k-lawrey , is it still relevant in the above use case?

https://stackoverflow.com/questions/12170952/where-can-i-find-some-sample-java-code-for-solarflare-openonload-kernel-bypass

**Comment by atwigg5678** [comment]
Hi

This functionality is available via Chronicle Queue Enterprise, please email me your details at andrew.twigg@chronicle.software and I can set you up with demo access

Regards
