### ISSUE TITLE
ConnectionManager.addListener executes synchronously for connections already present

### ISSUE THREAD

**Issue by nicktindall** [OpenHFT/Chronicle-Network#109]
When [`ConnectionManager.addListener`](https://github.com/OpenHFT/Chronicle-Network/blob/f503104936516d055a484d97d5005dbed215d455/src/main/java/net/openhft/chronicle/network/cluster/ConnectionManager.java#L38) is invoked it will execute the listener synchronously for any connections that are already present.

Usually the code in the listener is executed by the event loop thread, so callers might assume that is always the case and do things that should only be executed in the event loop thread. ~An example of an issue caused by this is https://github.com/ChronicleEnterprise/Chronicle-Services/issues/229.~

I think a better approach would be to keep track of new listeners and execute them in the event loop rather than synchronously in the add.

**Comment by nicktindall** [comment]
Update, I'm reasonably certain this is not the root cause of ChronicleEnterprise/Chronicle-Services#229 but I still think it could be an issue.

**Comment by RobAustin** [comment]
Will this proposal still work if you are using a concurrent event loop?

**Comment by nicktindall** [comment]
I'm not sure to be honest, I listened to the dev meeting recording and Jerry mentioned that in a concurrent event loop individual handlers are still bound to a single thread, so we'd need a way to ensure the listener was called by the same thread associated with the TCPHandler.

I'm not sure about the details, but you are passed a `net.openhft.chronicle.network.NetworkContext` in `net.openhft.chronicle.network.cluster.ConnectionManager.ConnectionListener.onConnectionChange` and NetworkContexts don't look to be thread-safe so it seems dangerous that these Listeners can end up executing on the thread that adds them.

**Comment by JerryShea** [comment]
~~ConnectionManager should definitely check it is only called on one thread~~. Ah its methods are synchronized.
Maybe we should have a ManagedThreadSafe (like ManagedCloseable), and give that the ability to check that it is running in an event loop thread?
@RobAustin I would propose that we give the ability to check if we are running in any event loop thread - @nicktindall's suggestion was we can just set a ThreadLocal when we start a thread from an event loop

**Comment by JerryShea** [comment]
Relates to https://github.com/OpenHFT/Chronicle-Core/issues/226

**Comment by peter-lawrey** [comment]
@nicktindall Is there any more to do for this issue?

**Comment by nicktindall** [comment]
> @nicktindall Is there any more to do for this issue?

I made a fix in Queue Enterprise which fixes the problem specifically when the ServerThreadingStrategy is not CONCURRENT. Which is an improvement, because I tried and its reasonably difficult to use CONCURRENT (you need to override the default EventGroup).

The problem in general is still there, and I'm not sure how to fix it generally. The issue is the TcpEventHandler manages the NetworkContext so if you call ConnectionManager.addListener and it ends up being executed synchronously on the calling thread there's a chance you'll be provided with a NetworkContext that is in the process of being closed.

There is an example of how to do this in a thread-safe manner [here](https://github.com/OpenHFT/Chronicle-Threads/blob/0ea446c474bbf23551f211eec09052fe002190d3/src/main/java/net/openhft/chronicle/threads/MediumEventLoop.java#L220) but its a bit more complicated in the case of the ConnectionManager because there's a chance that the ServerThreadingStrategy is CONCURRENT and each of the NetworkContexts is "owned" by a different thread.

**Comment by nicktindall** [comment]
The idea behind [this issue](https://github.com/OpenHFT/Chronicle-Core/issues/226) was that we might be able to add assertions to pick up these things in testing. For me (and, I assume, whoever wrote that code) it was a surprise that the event handler could be executed synchronously to introduce this issue.
