### ISSUE TITLE
Don't call onMissedHeartbeat if connection is closed

### ISSUE THREAD

**Issue by jkolobok** [OpenHFT/Chronicle-Network#112]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Network-2.21ea66](https://github.com/OpenHFT/Chronicle-Network/releases/chronicle-network-2.21ea66), [BOM-2.21ea170](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.21ea170)

**Comment by JerryShea** [comment]
Context for this change: https://support.chronicle.software/staff/ticket/211
