### ISSUE TITLE
ClusterAcceptorEventHandler accumulates NetworkContexts over time

### ISSUE THREAD

**Issue by nicktindall** [OpenHFT/Chronicle-Network#115]
There is a memory leak in ClusterAcceptorEventHandler whereby it collects a NetworkContext every time it establishes a connection and they aren't cleared until the event handler is closed.
This can amount to a lot of garbage for a long-running node.

See https://github.com/OpenHFT/Chronicle-Network/blob/c63ab5b356eb0fd3bf5d80b26b6623a642b4b064/src/main/java/net/openhft/chronicle/network/cluster/ClusterAcceptorEventHandler.java#L66

These probably don't need to be accumulated here as they should be closed when the TcpEventHandler is closed.

https://github.com/OpenHFT/Chronicle-Network/blob/c63ab5b356eb0fd3bf5d80b26b6623a642b4b064/src/main/java/net/openhft/chronicle/network/TcpEventHandler.java#L480

**Comment by hft-team-city** [comment]
Released in [Chronicle-Network-2.21ea69](https://github.com/OpenHFT/Chronicle-Network/releases/chronicle-network-2.21ea69), [BOM-2.21ea177](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.21ea177)
