### ISSUE TITLE
Don't attempt to reconnect an initiator if it's closed

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Network#117]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Network-2.21ea69](https://github.com/OpenHFT/Chronicle-Network/releases/chronicle-network-2.21ea69), [BOM-2.21ea177](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.21ea177)
