### ISSUE TITLE
Some checks for misconfiguration are assertions

### ISSUE THREAD

**Issue by nicktindall** [OpenHFT/Chronicle-Network#124]
There are some assertions that check states that can be the result of misconfiguration. Because assertions are typically not enabled in production this could mean prod happily runs when it is misconfigured.

For example:
https://github.com/OpenHFT/Chronicle-Network/blob/fb09eac213ac81de17c5be52a94683475dc30c42/src/main/java/net/openhft/chronicle/network/cluster/handlers/UberHandler.java#L105
This can be the result of an mismatch between host ID and endpoint URL in a config file, we probably never want to proceed if the other end thinks we're someone else. This should probably result in a logged error and immediate disconnection.

**Comment by JerryShea** [comment]
Likewise asserts in HeartbeatHandler constructor

**Comment by hft-team-city** [comment]
Released in [Chronicle-Network-2.21ea87](https://github.com/OpenHFT/Chronicle-Network/releases/chronicle-network-2.21ea87), [BOM-2.21ea208](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.21ea208)
