### ISSUE TITLE
Fix UberHandlerTest#testUberHandlerWithMultipleSubHandlersAndHeartbeats on ARM

### ISSUE THREAD

**Issue by alamar** [OpenHFT/Chronicle-Network#129]
net.openhft.chronicle.network.UberHandlerTest#testUberHandlerWithMultipleSubHandlersAndHeartbeats is broken on Linux ARM

**Comment by hft-team-city** [comment]
Released in [Chronicle-Network-2.21ea85](https://github.com/OpenHFT/Chronicle-Network/releases/chronicle-network-2.21ea85), [BOM-2.21ea206](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.21ea206)
