### ISSUE TITLE
Serializing FatalFailureConnectionStrategy from YAML config triggers NPE

### ISSUE THREAD

**Issue by glukos** [OpenHFT/Chronicle-Network#149]
```
    private final transient AtomicBoolean isClosed = new AtomicBoolean(false);
```
This filed is transient and remains `null` after `Marshallable.fromString`

**Comment by hft-team-city** [comment]
Released in [Chronicle-Network-2.22ea5](https://github.com/OpenHFT/Chronicle-Network/releases/chronicle-network-2.22ea5), [BOM-2.22ea50](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea50)
