### ISSUE TITLE
UDP Roadmap

### ISSUE THREAD

**Issue by scottkidder** [OpenHFT/Chronicle-Network#15]
What is the timeline/roadmap for UDP support?

**Comment by TerryW9** [comment]
Hi Scott,

Thank you for the question.
I will find out and get back to you as soon as possible.

Best Regards,
Terry

**Comment by peter-lawrey** [comment]
Hi Scott,
We would add support when we have a use case in mind. We could consider Aeron for example, provided it was talking to another system using Aeron, but it depends on the specific use case.
If you have a use case in mind I am happy to discuss it over email/phone.

Regards,
  Peter.
