### ISSUE TITLE
When WritableSubHandlers are removed from an UberHandler they are left in the writers list

### ISSUE THREAD

**Issue by nicktindall** [OpenHFT/Chronicle-Network#157]
If a WritableSubHandler throws a RejectedHandlerException, or any other scenario that leads to them being removed, the removal leaves them in the list of writers so onWrite continues to be called despite the handler being removed for receiving messages.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Network-2.22ea7](https://github.com/OpenHFT/Chronicle-Network/releases/chronicle-network-2.22ea7), [BOM-2.22ea69](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea69)
