### ISSUE TITLE
Added SSL support and tests

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Network#16]

**Comment by RobAustin** [comment]
done - see /Users/robaustin/git-projects/Chronicle-Network/src/test/java/net/openhft/chronicle/network/ssl

**Comment by dpisklov** [comment]
@RobAustin strange, that path doesn't exist for me - do you know what might be the reason? ;D

**Comment by RobAustin** [comment]
try https://github.com/OpenHFT/Chronicle-Network/tree/master/src/main/java/net/openhft/chronicle/network/ssl

**Comment by hft-team-city** [comment]
Released in Chronicle-Network-2.17.1 (https://github.com/OpenHFT/Chronicle-Network/releases/chronicle-network-2.17.1), BOM-2.17.42 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.42)

**Comment by hft-team-city** [comment]
Released in Chronicle-Network-2.17.1 (https://github.com/OpenHFT/Chronicle-Network/releases/chronicle-network-2.17.1), BOM-2.17.44 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.44)

**Comment by hft-team-city** [comment]
Released in Chronicle-Network-2.17.1 (https://github.com/OpenHFT/Chronicle-Network/releases/chronicle-network-2.17.1), BOM-2.17.46 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.46)

**Comment by hft-team-city** [comment]
Released in Chronicle-Network-2.17.1 (https://github.com/OpenHFT/Chronicle-Network/releases/chronicle-network-2.17.1), BOM-2.17.48 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.48)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Network-2.17.1](https://github.com/OpenHFT/Chronicle-Network/releases/chronicle-network-2.17.1), [BOM-2.17.50](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.50)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Network-2.17.1](https://github.com/OpenHFT/Chronicle-Network/releases/chronicle-network-2.17.1), [BOM-2.17.52](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.52)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Network-2.17.1](https://github.com/OpenHFT/Chronicle-Network/releases/chronicle-network-2.17.1), [BOM-2.17.53](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.53)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Network-2.17.1](https://github.com/OpenHFT/Chronicle-Network/releases/chronicle-network-2.17.1), [BOM-2.17.60](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.60)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Network-2.17.1](https://github.com/OpenHFT/Chronicle-Network/releases/chronicle-network-2.17.1), [BOM-2.17.72](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.72)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Network-2.17.1](https://github.com/OpenHFT/Chronicle-Network/releases/chronicle-network-2.17.1), [BOM-2.17.74](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.74)
