### ISSUE TITLE
Registerable and ConnectionListener SubHandlers aren't unregistered/removed from listeners on reject

### ISSUE THREAD

**Issue by nicktindall** [OpenHFT/Chronicle-Network#160]
- SubHandlers that implement `Registerable` should be unregistered when they reject
- SubHandlers that implement `ConnectionListener` should be removed from the listeners when they reject

**Comment by hft-team-city** [comment]
Released in [Chronicle-Network-2.22ea7](https://github.com/OpenHFT/Chronicle-Network/releases/chronicle-network-2.22ea7), [BOM-2.22ea69](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea69)
