### ISSUE TITLE
VanillaClusteredNetworkContext passes `this` to NetworkStatsListener from its constructor

### ISSUE THREAD

**Issue by nicktindall** [OpenHFT/Chronicle-Network#162]
See https://github.com/OpenHFT/Chronicle-Network/blob/6d3b4d145358d97d023196a2fa455a077c93b69d/src/main/java/net/openhft/chronicle/network/cluster/VanillaClusteredNetworkContext.java#L26-L30

Consequently under some circumstances you can't interact with `NetworkContext` in `NetworkStatsListener#networkContext(NetworkContext)` or you'll be interacting with an uninitialised `NetworkContext`

**Comment by hft-team-city** [comment]
Released in [Chronicle-Network-2.22ea7](https://github.com/OpenHFT/Chronicle-Network/releases/chronicle-network-2.22ea7), [BOM-2.22ea69](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea69)
