### ISSUE TITLE
ConnectionListener#onDisconnected is called twice for every disconnect

### ISSUE THREAD

**Issue by nicktindall** [OpenHFT/Chronicle-Network#164]
(when using the UberHandler at least)

It's called here

https://github.com/OpenHFT/Chronicle-Network/blob/5d53d322e4b1713c6e8ce24326038f4e382a0b53/src/main/java/net/openhft/chronicle/network/cluster/handlers/UberHandler.java#L157

and here

https://github.com/OpenHFT/Chronicle-Network/blob/5d53d322e4b1713c6e8ce24326038f4e382a0b53/src/main/java/net/openhft/chronicle/network/cluster/handlers/HeartbeatHandler.java#L227-L228

**Comment by hft-team-city** [comment]
Released in [Chronicle-Network-2.24ea2](https://github.com/OpenHFT/Chronicle-Network/releases/chronicle-network-2.24ea2), [BOM-2.24ea6](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24ea6)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Network-2.23.23](https://github.com/OpenHFT/Chronicle-Network/releases/chronicle-network-2.23.23), [BOM-2.23.131](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23.131)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Network-2.22.16](https://github.com/OpenHFT/Chronicle-Network/releases/chronicle-network-2.22.16), [BOM-2.22.165](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22.165)
