### ISSUE TITLE
Add atomic VanillaNetworkContext.close() method to avoid race condition

### ISSUE THREAD

**Issue by gordonnb** [OpenHFT/Chronicle-Network#17]
I found a bug in this method exposed by occasional failure of FIX AcceptorInitiatorTest.testStartAndEndOfConnection()

Basically both the main thread and the event-loop-thread of the client FixEngine would attempt to call FixNetworkContext.close() and in fact enter the method simultaneously owing to lack of mutex.  This would result in listener being notified twice and failing the test.

I think making the FixNetworkContext.close() method synchronised as in the base class is dangerous because it invokes listeners that could potentially do something to deadlock.  And it would be better to avoid locks altogether.

My suggestion instead is to add a new VanillaNetworkContext.closeWithCAS() method to return boolean if state is actually changed (using AtomicBoolean member instead of volatile boolean).

**Comment by TerryW9** [comment]
Hi Gordon,

Thank you for logging this issue.
We will prioritise it accordingly.

Best Regards,
Terry
