### ISSUE TITLE
Connection reset exceptions are no longer reliably suppressed

### ISSUE THREAD

**Issue by nicktindall** [OpenHFT/Chronicle-Network#172]
We have code in TCPEventHandler to log connection reset errors at TRACE level, where other connection errors are logged at DEBUG or WARN. There is no specific exception for connection reset so we inspect `IOException`s to see if they look like one of the exceptions thrown when reading from/writing to a reset connection.

https://github.com/OpenHFT/Chronicle-Network/blob/76ffaf7b06811254c3dc61c408d2cf881d8eef48/src/main/java/net/openhft/chronicle/network/TcpEventHandler.java#L478

In JDKs 13 and above, a new one of these has been introduced.
https://github.com/openjdk/jdk/commit/3a4d5db248d74020b7448b64c9f0fc072fc80470

We should detect that as well so we don't log spurious warnings.

**Comment by alamar** [comment]
There's also a problem when using non-English locale: the messages are different for every language and there's no way to get un-localized one. So when running on French or Chinese-language box, these messages will never be suppressed.

**Comment by minborg** [comment]
> There's also a problem when using non-English locale: the messages are different for every language and there's no way to get un-localized one. So when running on French or Chinese-language box, these messages will never be suppressed.

This is as true as it is ridiculous. I fail to understand why any programmer ever would use a language other than English.

**Comment by nicktindall** [comment]
> There's also a problem when using non-English locale: the messages are different for every language and there's no way to get un-localized one. So when running on French or Chinese-language box, these messages will never be suppressed.

I think we might be "safe" because we use [getMessage](https://docs.oracle.com/javase/8/docs/api/java/lang/Throwable.html#getMessage--) not [getLocalizedMessage](https://docs.oracle.com/javase/8/docs/api/java/lang/Throwable.html#getLocalizedMessage--) but this is a dirty hack and we shouldn't be doing it anyway. I will spend a little but of time looking into whether we can do it without relying on the message.

**Comment by alamar** [comment]
@minborg Locale dictates things such as date format, number formatting, currency sign, etc, so it is important for an application to run in a correct locale. However, non-English locales will also cause some Java error messages to change. This made sense if you expect to show the exception message to the end-user, but it's a big problem of Java that you can't tell "connection reset" by looking at IOException.

@nicktindall Unfortunately, `getMessage()` is also localized :) :( and `getLocalizedMessage()` just returns `getMessage()`.

**Comment by minborg** [comment]
> @minborg Locale dictates things such as date format, number formatting, currency sign, etc, so it is important for an application to run in a correct locale. However, non-English locales will also cause some Java error messages to change. This made sense if you expect to show the exception message to the end-user, but it's a big problem of Java that you can't tell "connection reset" by looking at IOException.
> 
> @nicktindall Unfortunately, `getMessage()` is also localized :) :( and `getLocalizedMessage()` just returns `getMessage()`.

I fully support the use of Locale but changing language is just wrong.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Network-2.22ea12](https://github.com/OpenHFT/Chronicle-Network/releases/chronicle-network-2.22ea12), [BOM-2.22ea121](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea121)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Network-2.23ea0](https://github.com/OpenHFT/Chronicle-Network/releases/chronicle-network-2.23ea0), [BOM-2.22.129](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22.129)
