### ISSUE TITLE
net.openhft.chronicle.bytes.util.DecoratedBufferUnderflowException: readPosition failed. Position: 838 > readLimit: 834

### ISSUE THREAD

**Issue by sthekepat** [OpenHFT/Chronicle-Network#18]
Really don't know what's to be done.
The heart beat messages are routed also to my inherited class of WireTcpHandler, i.e in the onRead() method.
So If I read using in.wire().read("heartbeat") to see if it's null, it bails out on my read "payload" messages.
If I read in.wire().read("payload") if bails on "heartbeat" messages.
A heartbeat message handler should be installed automatically???
Why should my code have to handle heartbeat messages also?
Am I doing something wrong?

Thanks,
TJ

**Comment by peter-lawrey** [comment]
It depends on what you are trying to achieve, but if you don't know which
event name or field to expect, I suggest readEventName and parsing based on
that.
Note: there is support for this. You can create a MethodReader which turns
each message into a method call of the same name. BTW MethodWriter writes
each method call as an event. e.g.

I have added an example of such a TCP handler
net.openhft.chronicle.network.MethodTcpHandler.  This will handle all the
decoding and encoding of method calls, so all you need to do is provide the
implementation.  This needs some tests and docs, but I believe this would
make your code simpler.

Peter.
ᐧ
