### ISSUE TITLE
Move SocketExceptionUtil functionality to IOTools in Core

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Network#201]
Deprecate SEU once IOTools is released https://github.com/OpenHFT/Chronicle-Core/issues/436 
@nicktindall fyi

**Comment by RobAustin** [comment]
@alamar can you check this is done and close

**Comment by hft-team-city** [comment]
Released in [Chronicle-Network-2.24ea1](https://github.com/OpenHFT/Chronicle-Network/releases/chronicle-network-2.24ea1), [BOM-2.24ea6](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24ea6)
