### ISSUE TITLE
IOException thrown when a read from a FastJ8SocketChannel fails due to the underying channel being closed

### ISSUE THREAD

**Issue by nicktindall** [OpenHFT/Chronicle-Network#214]
It should throw `ClosedChannelException` like the other implementations do (this is handled in lots of places)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Network-2.24ea1](https://github.com/OpenHFT/Chronicle-Network/releases/chronicle-network-2.24ea1), [BOM-2.24ea6](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24ea6)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Network-2.23.23](https://github.com/OpenHFT/Chronicle-Network/releases/chronicle-network-2.23.23), [BOM-2.23.131](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23.131)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Network-2.22.16](https://github.com/OpenHFT/Chronicle-Network/releases/chronicle-network-2.22.16), [BOM-2.22.165](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22.165)
