### ISSUE TITLE
ConnectionListener is being triggered twice upon disconnect

### ISSUE THREAD

**Issue by foroughgoudarzi** [OpenHFT/Chronicle-Network#218]

**Comment by RobAustin** [comment]
I suspect this is being caused by the heartbeat handler also triggering an onDisconnect, I question if it is necessary for the heartbeat handler to be registered as a connection listener

**Comment by JerryShea** [comment]
Duplicate of #164?

**Comment by nicktindall** [comment]
This is a duplicate of #164, will close it
