### ISSUE TITLE
Allow binding of socket for outgoing connections

### ISSUE THREAD

**Issue by nicktindall** [OpenHFT/Chronicle-Network#236]
Implementation to support https://github.com/ChronicleEnterprise/Chronicle-FIX/issues/1673

**Comment by hft-team-city** [comment]
Released in [Chronicle-Network-2.24ea9](https://github.com/OpenHFT/Chronicle-Network/releases/chronicle-network-2.24ea9), [BOM-2.24ea53](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24ea53)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Network-2.23.28](https://github.com/OpenHFT/Chronicle-Network/releases/chronicle-network-2.23.28), [BOM-2.23.166](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23.166)
