### ISSUE TITLE
When a reconnection is triggered by the HeartbeatCheckHandler it can result in reconnects being aborted

### ISSUE THREAD

**Issue by nicktindall** [OpenHFT/Chronicle-Network#240]
The socketReconnector being triggered from the HeartbeatCheckHandler kicks off the reconnection on the blocking event loop, and then closes the associated UberHandler which in-turn closes the network context.

When the TcpHandler executes next time it will throw an InvalidEventHandler exception because of the closed socketChannel, which will cause it to be removed from the event loop and its close method to be called.

In the TcpEventHandler close method it calls `socketReconnector().close()` on the old socketReconnector, which itself calls HostConnector.close (which isn't really a close method it's more of a reset method).

The problem is by the time this happens, it's possible we've populated the HostConnector with the new NetworkContext (the one created for the reconnection). So when the reconnection happens and we attempt to set the socketChannel on it, it throws a ClosedIllegalState exception, which causes the RCEventHandler to  be silently removed from the event loop, with no reconnect scheduled.

This leaves the node in a state where it is disconnected and not attempting reconnection. :sweat:

**Comment by hft-team-city** [comment]
Released in [Chronicle-Network-2.23.28](https://github.com/OpenHFT/Chronicle-Network/releases/chronicle-network-2.23.28), [BOM-2.23.166](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23.166)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Network-2.24ea10](https://github.com/OpenHFT/Chronicle-Network/releases/chronicle-network-2.24ea10), [BOM-2.24ea55](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24ea55)
