### ISSUE TITLE
Outright remove tcp.unchecked.buffer property

### ISSUE THREAD

**Issue by alamar** [OpenHFT/Chronicle-Network#245]
It is not tested anywhere and prevents SSL from working with cryptic error "AEADBadTagException: Tag mismatch!"

It was not enabled anywhere for prolonged period of time. It is also not documented anywhere, making it a good target for removal.

**Comment by alamar** [comment]
Apparently it was only added in 2023, so it makes sense to diagnose and fix it instead

**Comment by peter-lawrey** [comment]
It makes a significant difference to benchmarks and as such is set from the command line.
However, it should never be true for SSL,as this doesn't work, nor is there a good reason to make it work given it would make little difference in that case.
