### ISSUE TITLE
Capturing lambda in ConnectionManager generates garbage each time a connection is established/disconnected

### ISSUE THREAD

**Issue by nicktindall** [OpenHFT/Chronicle-Network#252]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Network-2.24ea11](https://github.com/OpenHFT/Chronicle-Network/releases/chronicle-network-2.24ea11), [BOM-2.24ea56](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24ea56)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Network-2.23.32](https://github.com/OpenHFT/Chronicle-Network/releases/chronicle-network-2.23.32), [BOM-2.23.171](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23.171)
