### ISSUE TITLE
Increase unit test coverage

### ISSUE THREAD

**Issue by tgd** [OpenHFT/Chronicle-Network#262]
Increase unit test coverage for `TCPRegistry` and `AlwaysStartOnPrimaryConnectionStrategy`

**Comment by hft-team-city** [comment]
Released in [Chronicle-Network-2.24ea15](https://github.com/OpenHFT/Chronicle-Network/releases/chronicle-network-2.24ea15), [BOM-2.24ea74](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24ea74)
