### ISSUE TITLE
Fixed cluster context to consume padding when reading text wire

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Network#34]

**Comment by RobAustin** [comment]
I've moved this change to consume padding into wireParser().parseOne(wire) so that all messages can benefit from it.

**Comment by hft-team-city** [comment]
Released in Chronicle-Network-1.16.0 (https://github.com/OpenHFT/Chronicle-Network/releases/chronicle-network-1.16.0), BOM-1.16.8 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.16.8)
