### ISSUE TITLE
Fixed LoggingNetworkStatsListener to use JVM.debug() rather than directly use the SLF logger

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Network#35]

**Comment by hft-team-city** [comment]
Released in Chronicle-Network-1.16.0 (https://github.com/OpenHFT/Chronicle-Network/releases/chronicle-network-1.16.0), BOM-1.16.8 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.16.8)
