### ISSUE TITLE
ConnectionStrategy change to use System currentTimeMillis instead of tickTime()

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Network#36]
A client has ask that we change ConnectionStrategy to use System currentTimeMillis instead of tickTime()

**Comment by hft-team-city** [comment]
Released in Chronicle-Network-1.16.4 (https://github.com/OpenHFT/Chronicle-Network/releases/chronicle-network-1.16.4), BOM-1.16.154 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.16.154)

**Comment by hft-team-city** [comment]
Released in Chronicle-Network-1.16.4 (https://github.com/OpenHFT/Chronicle-Network/releases/chronicle-network-1.16.4), BOM-1.16.170 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.16.170)
