### ISSUE TITLE
Determine the TCP_BUFFER size from what the kernel allows

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Network#37]

**Comment by hft-team-city** [comment]
Released in Chronicle-Network-1.16.5 (https://github.com/OpenHFT/Chronicle-Network/releases/chronicle-network-1.16.5), BOM-1.16.170 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.16.170)
