### ISSUE TITLE
Minimum time between attempts to reconnect

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Network#41]
See net.openhft.chronicle.network.ConnectionStrategy#pauseMillisBeforeReconnect and net.openhft.chronicle.network.AlwaysStartOnPrimaryConnectionStrategy#pauseMillisBeforeReconnect

I would appreciate a review from the original authors @RobAustin @peter-k-lawrey @dpisklov 

See also https://github.com/ChronicleEnterprise/Chronicle-FIX/issues/299

**Comment by RobAustin** [comment]
I’ll review this code.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Network-2.17.3](https://github.com/OpenHFT/Chronicle-Network/releases/chronicle-network-2.17.3), [BOM-2.17.72](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.72)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Network-2.17.3](https://github.com/OpenHFT/Chronicle-Network/releases/chronicle-network-2.17.3), [BOM-2.17.74](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.74)
