### ISSUE TITLE
Added clusterContext.retryInterval(<value>) to it configurable

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Network#42]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Network-2.17.4](https://github.com/OpenHFT/Chronicle-Network/releases/chronicle-network-2.17.4), [BOM-2.17.72](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.72)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Network-2.17.4](https://github.com/OpenHFT/Chronicle-Network/releases/chronicle-network-2.17.4), [BOM-2.17.74](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.74)
