### ISSUE TITLE
AlwaysStartOnPrimaryConnectionStrategy doesn't honor Thread interruption

### ISSUE THREAD

**Issue by dkhamitov** [OpenHFT/Chronicle-Network#46]
If a host is unavailable and connection thread is interrupted, i.e. the JVM is being terminated, then AlwaysStartOnPrimaryConnectionStrategy starts an infinite loop of connection fails. Technically, it alternates between https://github.com/OpenHFT/Chronicle-Network/blob/60d1c2c4e67e0c69bee9f99a96b88ff348963400/src/main/java/net/openhft/chronicle/network/ConnectionStrategy.java#L112, https://github.com/OpenHFT/Chronicle-Network/blob/60d1c2c4e67e0c69bee9f99a96b88ff348963400/src/main/java/net/openhft/chronicle/network/AlwaysStartOnPrimaryConnectionStrategy.java#L86 and https://github.com/OpenHFT/Chronicle-Network/blob/60d1c2c4e67e0c69bee9f99a96b88ff348963400/src/main/java/net/openhft/chronicle/network/AlwaysStartOnPrimaryConnectionStrategy.java#L64
The issue was discovered while working with Chronicle-Fix engine

**Comment by hft-team-city** [comment]
Released in [Chronicle-Network-2.17.11](https://github.com/OpenHFT/Chronicle-Network/releases/chronicle-network-2.17.11), [BOM-2.17.366](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.366)
