### ISSUE TITLE
Make the target write size configurable

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Network#49]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Network-2.17.26](https://github.com/OpenHFT/Chronicle-Network/releases/chronicle-network-2.17.26), [BOM-2.17.537](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.537)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Network-2.17.26](https://github.com/OpenHFT/Chronicle-Network/releases/chronicle-network-2.17.26), [BOM-2.17.541](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.541)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Network-2.17.26](https://github.com/OpenHFT/Chronicle-Network/releases/chronicle-network-2.17.26), [BOM-2.17.544](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.544)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Network-2.17.26](https://github.com/OpenHFT/Chronicle-Network/releases/chronicle-network-2.17.26), [BOM-2.17.546](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.546)
