### ISSUE TITLE
Suspicious code in AbstractStatelessClient

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Network#58]
The following code might fail if the condition is true:

```
        if (resultType == CharSequence.class && usingValue != null)
            return f -> {
                f.textTo((StringBuilder) usingValue);
                return usingValue;
            };
```

If the `resultType` is equal `CharSequence`, then, by definition, it is not a `StringBuilder` even though the `usingValue` might be a `StringBuilder`

**Comment by hft-team-city** [comment]
Released in [Chronicle-Network-2.21ea69](https://github.com/OpenHFT/Chronicle-Network/releases/chronicle-network-2.21ea69), [BOM-2.21ea177](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.21ea177)
