### ISSUE TITLE
AbstractStatelessClient::toParameters is using double dynamic lambda

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Network#59]
This creates unnecessary lambda instantiations for calls with two or more parameters.

**Comment by minborg** [comment]
for example "put(key, value)" will suffer.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Network-2.24ea5](https://github.com/OpenHFT/Chronicle-Network/releases/chronicle-network-2.24ea5), [BOM-2.24ea29](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24ea29)
