### ISSUE TITLE
Allow the VanillaNetworkContext to be used for all network contexts

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Network#61]
Allow the VanillaNetworkContext to be used for all network context so that a single port can serve a number of uses, in other words, remove the

```
QueueClusterNetworkContext
DatagridWireNetworkContext
MapClusterNetworkContext
```

and allow all the data to be stored and configured into the VanillaNetworkContext

**Comment by dpisklov** [comment]
@RobAustin where we are with this?

**Comment by RobAustin** [comment]
It has not been done yet, we should release all the current changes on Datagrid and fix before introducing another enhancement ( like this )

**Comment by dpisklov** [comment]
Don't think this is ever going to happen - @RobAustin ?
