### ISSUE TITLE
Make TcpEventHandler's write bias configurable

### ISSUE THREAD

**Issue by dpisklov** [OpenHFT/Chronicle-Network#80]
At the moment TcpEventHandler is either read-biased (default) or fair. There're use cases where write bias can be more efficient (e.g. source side of the replication)

FYI @JerryShea

**Comment by hft-team-city** [comment]
Released in [Chronicle-Network-2.19.48](https://github.com/OpenHFT/Chronicle-Network/releases/chronicle-network-2.19.48), [BOM-2.19.280](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.19.280)
