### ISSUE TITLE
Add internal copy-free buffers for TcpEventHandler 

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Network#85]
The `TcpEventHandler`'s internal write and read overhead is ~`O(N^2)`, where N is the number of messages buffered. This means that the handler's capacity will hit a steep performance cliff at a certain workload.

**TL;DR**

*100k msg/s*
For example, if 100k messages per second are written to a socket and each message is 100 bytes and the saturated socked can accept 100 messages per write attempts and there is a 100 ms latency in steady-state:

- There are 0.1*100k = 10 k messages in the send queue.
- The 10k messages will occupy 10k*100 = 1 MB ByteBuffer capacity
- There will be 100k/100  = 1000 socket write attempts per second
- The `ByteByffer::compact` operation will have to copy 1 MB 1000 times per second = 1 GB/s

*200k msg/s*
For example, if 200k messages per second are written to a socket and each message is 100 bytes and the saturated socked can accept 100 messages per write attempts and there is a 100 ms latency in steady-state:

- There are 0.1*200k = 20 k messages in the send queue.
- The 20k messages will occupy 20k*100 = 2 MB ByteBuffer capacity
- There will be 200k/100  = 2000 socket write attempts per second
- The `ByteByffer::compact` operation will have to copy 2 MB 2000 times per second = 4 GB/s

Thus, the internal write overhead is ~`O(N^2)`. The problem with reading will under some conditions be similar.

*Details*

The internals of the class can be outlined like this:

<img width="1011" alt="TcpEventHandler" src="https://user-images.githubusercontent.com/7457876/86940528-3d155800-c143-11ea-8380-e3b318cee919.png">

This picture shows how `ByteBuffer::compact` is invoked for every second message sent (assuming that the saturated socket could absorb 2 messages per call on average).

<img width="618" alt="InBBB" src="https://user-images.githubusercontent.com/7457876/86940568-47cfed00-c143-11ea-8001-ab23766f7766.png">

It would be better to use a copy-free scheme (e.g. a ring-buffer or a reusable ByteBuffer slice) as shown here:

<img width="1022" alt="CircularInBBB" src="https://user-images.githubusercontent.com/7457876/86940818-8796d480-c143-11ea-9073-b2e581573da8.png">

**Comment by minborg** [comment]
Invoking `Buffer::compact` on large buffer will also introduce `EventHandler` jitter and severely impact CPU caching efficiency.

**Comment by minborg** [comment]
A relatively simple solution would be to create a round-robin use of `Bytes` which would have several benefits including not having to use `underlying()` at all.

**Comment by RobAustin** [comment]
@minborg I see you have done some work on this can we close it ? Otherwise please outline what else is remaining to do.

**Comment by RobAustin** [comment]
@glukos this is not a priority at the moment, but when you get back to network enterprise could you also consider this issue. Thanks.

**Comment by minborg** [comment]
Once you start with this @glukos, I could provide some additional background information as well as ideas I had in the past with regards to the issue at hand.

**Comment by minborg** [comment]
See the branch feature/doublebuffer for how I initially thought to solve this

**Comment by jkolobok** [comment]
@minborg I don't see this branch anymore.  
Since ring buffer is a commercial feature we cannot use it unless implement something similar. Do we want this?

**Comment by minborg** [comment]
I think this issue is important to fix. I think the branch was removed. Perhaps it is better to start afresh since this issue was written in 2020

**Comment by minborg** [comment]
So, the `compactBuffer()` is only called when we have read a quarter of the `TCP_BUFFER` and this makes the problem much smaller than described above. We would still benefit from using a ring buffer but that is likely only going to reduce jitter and not the performance so much. I am closing this now.

```
        } else if (inBBB.readPosition() > TCP_BUFFER / 4) {
            compactBuffer();
            busy = true;
        }
```
