### ISSUE TITLE
HostConnector should not implement abstract closable, because this prevents reconnects working on failover

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Network#86]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Network-2.19.74](https://github.com/OpenHFT/Chronicle-Network/releases/chronicle-network-2.19.74), [BOM-2.19.349](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.19.349)
