### ISSUE TITLE
Simplify VanillaWireOutPublisher

### ISSUE THREAD

**Issue by dpisklov** [OpenHFT/Chronicle-Network#90]
Need to  extract `consumers` to Datagrid (the only project where it is used)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Network-2.20.100](https://github.com/OpenHFT/Chronicle-Network/releases/chronicle-network-2.20.100), [BOM-2.20.136](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.136)
