### ISSUE TITLE
FastJ8SocketChannel accesses FileDescriptor outside locks

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Network#98]
The (partly) delegated `SocketChannel` is sharing the `FileDescriptor fd` with `FastJ8SocketChannel` itself. The `fd` is always protected in the `SocketChannelImpl` using the `stateLock` but in the `FastJ8SocketChannel` another lock (`readLock`) is used. 

This means that two threads can access the `fd` concurrently and that the state in SocketChannelImpl may become invalid, for example, if the `configureBlocking` method is invoked?

**Comment by RobAustin** [comment]
@glukos could you investigate this and maybe fix

**Comment by glukos** [comment]
`read` is the only operation in which `fd` is accessed directly in `FastJ8SocketChannel`.
I think we can just reuse `SocketChannelImpl#readLock` in order to guarantee consistency of other operations that should be synchronized with reading, like `bind`, `connect`, etc.
